language: node_js
node_js: 6
cache:
  directories:
  - node_modules
notifications:
  email: false
  pushover:
    api_key:
      secure: VmadUsFvNT6VqyVTfdofX5/za8YKaYGrFF/qZ2sSe2PJDMaP1gOM9MjbwGk3XjtMtJGxYGC/FNI5JgEz+TBOWISyHK39hCn1xrnHgmLbZycAXa7HB7AUy15d2tURh78mcqiZvLcbqjbYXuIszn6JnPcU+yW5wIFbga3yFQhkA15Irfq05dHG020fnsNuXhxpkbBzjndMkLBwVckJzyeB8yj8k201/ARAxAoNMFQNP7/q2/ATE7dKHNXk/sYlfhxolaLwDsS2D044R+HHv9SuAayTxes8439Ad7sSGigUoWDp6c6ICm5/Jue79mPzcAAHx9PaEYZbEjmU7iHAsJFQizvNzeVmF6yVJ2z6I9o3BBzXSeW0oLJLIgj+AairlU3RLEHSIxu0paltLVJB+GFTJYrRjJE4iirEfVbFAgmxjiul+l0VWsE+/VKwViP9X5+UV2b6/JGu7qa1e0bY5RdlM+Mp9lhScvoUR821BXNwLtsi7izDKslz6FdHE7NxkLHSbNyTNb6sOsOQ8A205tX2xRknT27KovcZoNuT0r+FmHXk26LEJmXC5TxkHknrc6Fuwgn8pu2uAgsQd8iUomqmCu/0NTCAgGPg88MIw25ZBCarEdFp85vlNn2V4C4WQGJbajm8w21fNIZjVpuliU6s9PpDsoGU2s7r4wH4PAQpklg=
    users:
      secure: mKs0D89Bdfa/Z76rWuqE8lM60ikUrl5s5opzoUs8AmtE8rA1Jw9MxLodsYheX2a7Hygz1o38uuApvGSbdSuqewDtbhYbE/Y0fHmoEccgyhhz1kgsb1jhYscDxMuDI4uYtVM7JiOg7+IDiFNrgzQ0LfL/MVkParYofdNDWVVI/oZTLDFpUx7rbbZEbMYpImCmEPFzOOWRqVw7rhRcANCUVDBxAxwAqtIHP8RonwfwS9RdIIFe48YE/vafEigStPbD7uND76TXTHKVPuA0guhyhidS6EQOVFmCbKjwDZdNw+jlX50aRkPGcw7yIFc3QyrCpOWLkDCw6FQIsnuUyRRUM9KC+BGsnohnXXHRS9UuxwQT6jC8XltJzlXhFt8Ugp/JFhO2yivn6bp84mZjxUwOKJl41sYfyNz9fUKvsf47wW7E8XD6MCycKaRS9EckOdU5aeU7zg3761byo7tLm0n3SE7DCen+PKGVcwsJCsZX3Ybahh74AJ1O0tDBht6jtUXu2i2MkCxLhofI5sxZk4CWBqbLLot9fObQv+XJOtmAt5D6jOzOUMucVAc/vAcKCE5V7caT+81kqWxW9dM9rQpMCIj0w6RKVUOwmXtr5266NhqFyaM62f+DteoISAiK2RhwjYkHX3W88XZrWJ/PPUhf7B5l1aru1Z4hoTfrIBSxqTk=
